### ISSUE TITLE
Container Implementation

### ISSUE THREAD

**Issue by bbarad** [GrotjahnLab/surface_morphometrics#10]
It would be useful to build a container implementation to avoid some of the pitfalls of different operating system configurations with pymeshlab

**Comment by bbarad** [comment]
From Twitter discussion, seems like singularity is the best option for this - I'm not sure whether it would be better to just publish the recipe vs an image on one of the hubs

**Comment by truatpasteurdotfr** [comment]
I would publish both recipes (docker/singularity/apptainer/..) to foster collaboration and image for end-user to consume.
