### ISSUE TITLE
Documentation about output file types

### ISSUE THREAD

**Issue by GenevieveBuckley** [GrotjahnLab/surface_morphometrics#14]
In my discussion with Ben today, we talked a little bit about the different types of files output at different stages of the analysis. 

I'm copying my notes here for later reference, and ideally we'd also add this to the docs.

* Files with`.xyz` extension are the point clouds
* Files with `.ply` extension are the surface meshes
* Files with.`.surface.vtp` extension are also surface meshes
   * The `.surface..vtp` files are a less cross-compatible format, so you can't use them with as many types of software. Paraview can load this format, Ben used this for the analysis in the surface-morphometrics paper). Also, a python library called pyvista can load these files (could be good for writing an automated analysis pipeline).
   * The advantage is that it allows storing extra metadata about the mesh at each point. Potentially that could be used to do more types of analysis later on (possibly scripted with pyvista)
* ... Files with `.gt` extension are ....
* ... Files with`.csv` extension are ...
* ...Files with `.log` extension are log files ...

I should also add a note about which stage of the pipeline generates each one.

**Comment by bbarad** [comment]
Completed for upcoming 1.0 release
