### ISSUE TITLE
graph tool win x64

### ISSUE THREAD

**Issue by IsiMolina** [GrotjahnLab/surface_morphometrics#18]
Hi!
I hope everyone is doing well. 
So, I've been trying to use this on my computer, a windows 10 x64 but I noticed that conda-forge:graph tool isn't available for this operative system.  Could you give me a hint on how to bypass this problem?
Thank you in advance,
Isidora

**Comment by bbarad** [comment]
Hi Isidora,

Graph-tool has no windows support, so surface morphometrics can't be run natively in windows. However, we have been able to run the software using Ubuntu on Windows Subsystem for Linux (https://ubuntu.com/wsl) - this is a good way to run EMAN2 and other software as well!

Thanks,
Ben
