### ISSUE TITLE
Link to biorxiv paper?

### ISSUE THREAD

**Issue by GenevieveBuckley** [GrotjahnLab/surface_morphometrics#2]
What do you think about adding a link to the bioarxiv preprint in the readme? Eg: like this text at the bottom of the README page:

>  **A surface morphometrics toolkit to quantify organellar membrane ultrastructure using cryo-electron tomography**
Benjamin A. Barad, Michaela Medina, Daniel Fuentes, R. Luke Wiseman, Danielle A Grotjahn
bioRxiv 2022.01.23.477440; doi: https://doi.org/10.1101/2022.01.23.477440 

I personally found the paper helpful for understanding the broader picture, and application of the code. I think the people who stumble across the github repository first would also find it useful.

I also assume the paper is currently under review somewhere, and the citation information here could be updated once it's published (I'm guessing it might be a few months before that happens).

**Comment by bbarad** [comment]
Thanks for the suggestion! I've added citation information to the bottom - I'll be greatly expanding the readme and making a tutorial in the coming week or two so those will hopefully help provide additional context. I actually had open sourced this code well before the manuscript - ahead of the first talk we gave about the toolkit - so when I first wrote the readme there was no citation to reference...

**Comment by GenevieveBuckley** [comment]
Nice, looking forward to that! If there's example data available, I can volunteer to be a guinea pig for your tutorial materials (sadly we still have a little bit more work to do here before we are getting good membrane pixel segmentations on our own data).

And it makes total sense that the README was written much earlier - this was not a complaint at all, just something I thought would be helpful to include.

**Comment by bbarad** [comment]
We'll definitely have example data - working on the EMPIAR deposition but I might just drop a single segmentation on zenodo so we don't have to wait on it! I'll attach my updates to #4  if you want to follow there!
