### ISSUE TITLE
Minor alteration to fantastic workaround for mac users!

### ISSUE THREAD

**Issue by HDuyvesteyn** [GrotjahnLab/surface_morphometrics#29]
Hiya,

I have a 2023 Macbook Pro (M2 pro) Ventura and found that I had to make a slight alteration to the protocol for mac users when adding a library. It is necessary to add the 'set' flag.

conda env config vars set KMP_DUPLICATE_LIB_OK=TRUE

Also, worth noting that admin privellages are required to execute the install.

Just sharing in case helpful!

**Comment by bbarad** [comment]
Is this superseded by #8? I take it you aren't able to get this running after all? Last I checked (quite a while ago) there was a beta wheel for pymeshlab for mac, so we should be able to "just install" soon?

**Comment by bbarad** [comment]
Closing with #10 finished!
