### ISSUE TITLE
Pycurv fails without error for one of three labels

### ISSUE THREAD

**Issue by RHennellJames** [GrotjahnLab/surface_morphometrics#30]
I have a segmentation with 3 labels — Inner Membrane (IM), Outer Membrane (OM) and Vesicles (Ves). I ran segmentation_to_meshes.py and it outputs a *.surface.vtp file for each label, all of which look fine to me in ParaView.

However, when I run pycurv, for the Ves job it outputs the "The maximum curvature is likely off." error to the stdout file and after 8 minutes the job ends with no further output. There is a *Ves.VV_rh9.log file but it is empty with size 0 B. The pycurv handles the IM and OM *.surface.vtp files fine, and the output can be used by measure_distances_orientations.py with no issues.

The Ves label has a lot more individual surfaces that are smaller and more tightly curved than the other two membranes, so I thought it might be hitting a limit on a counter of some sort, but there is no error in either log. Can I try editing a variable in the config.yaml file to fix this?

**Comment by bbarad** [comment]
I think this might be related to #27... would you mind sharing your file that is failing with me? I can take it by email if you prefer not to post it publicly. I am finalizing a major update over the next week or two and am trying to work out all these performance issues with a simple container install...

**Comment by RHennellJames** [comment]
Hi @bbarad , I'm happy to share it but I'd prefer to send it by email. If you give me an email address I should be able to send it over the weekend.

**Comment by bbarad** [comment]
benjamin.barad@gmail.com works

**Comment by RHennellJames** [comment]
Hi @bbarad, I sent some files a few weeks ago but didn't get a response. I just wanted to check if you received my email?

**Comment by bbarad** [comment]
Sorry for the delay - we have been hard at work and found a working system that works for the example you sent on our end. Would you install from the git and confirm it works for you before I make a new release?

**Comment by RHennellJames** [comment]
Hi @bbarad 

It took a while to get the install sorted but it seems to be fixed. It took longer than the other labels but it finished without any errors.

Thanks for sorting this!

**Comment by bbarad** [comment]
Happy to hear it!
