### ISSUE TITLE
[Unexpected Output] All-NaN axis encountered when trying to measure intra-surface distances

### ISSUE THREAD

**Issue by deglushk** [GrotjahnLab/surface_morphometrics#36]
Greetings! :)

Running this awesome pipeline has been on my to-do list for quite a while, but until recently, I hadn’t dedicated enough time to it.

I’ve been struggling with the `measure_distances_orientations.py` script on my segmented data. The segmentation contains multiple labels (inner and outer nuclear envelopes, two plasma membranes). The curious thing is that about a month ago, I successfully ran the pipeline for a colleague’s segmented subtomo with a single labeled membrane, and everything worked perfectly.

For the past few days, I’ve been unable to get intra-surface distance measurements, no matter what changes I make to the config.yml file. I’ve even tried running the pipeline with just a single label. The meshes and .vtp files look normal when I inspect them in ParaView, and the pycurv calculations seem to complete successfully. All other scalar and vector features are calculated as expected. However, the intra-surface distances (`self_dist_min` and `self_dist_far`) are all NaN, and the self-IDs (`self_id_min` and `self_id_far`) are all -1.

Here’s an example from my latest run:

```
Input file specified - will run on meshes associated with this segmentation only
Distance and orientation settings:
Will measure intra-surface distances for:
['PM1']
Will also measure verticality for those surfaces
---------
0172_dose-filt_AT_fSIRT_z220to360_segmented
Intra-surface distances for ./0172_PM1/0172_dose-filt_AT_fSIRT_z220to360_segmented_PM1.AVV_rh10.gt
Loading graph and surface
Initializing variables
Calculating distances
/surface_morphometrics/intradistance_verticality.py:151: RuntimeWarning: All-NaN axis encountered
  print(np.nanmin(close_distances.a), np.nanmax(close_distances.a))
nan nan
/surface_morphometrics/intradistance_verticality.py:152: RuntimeWarning: All-NaN axis encountered
  print(np.nanmin(far_distances.a), np.nanmax(far_distances.a))
nan nan
Writing out distances
Writing out CSV: ./0172_PM1/0172_dose-filt_AT_fSIRT_z220to360_segmented_PM1.AVV_rh10.csv
Exporting graph data to CSV ./0172_PM1/0172_dose-filt_AT_fSIRT_z220to360_segmented_PM1.AVV_rh10.csv
Scalar Properties to save:  ['area', 'min_curvature', 'max_curvature', 'gauss_curvature', 'mean_curvature', 'orientation_class', 'kappa_1', 'kappa_2', 'gauss_curvature_VV', 'mean_curvature_VV', 'shape_index_VV', 'curvedness_VV', 'shape_index_cat', 'verticality', 'self_dist_min', 'self_id_min', 'self_dist_far', 'self_id_far']
Vector Properties to save:  ['xyz', 'normal', 'n_v', 't_v', 't_1', 't_2']
299999 "area" values
min = 0.06294413898448445, max = 1.1954993573505024, mean = 0.3670446329550797
299999 "min_curvature" values
min = -0.12375366324541347, max = 0.06043985671545506, mean = -0.005120682756560967
299999 "max_curvature" values
min = -0.06937317490938202, max = 0.11905248947116635, mean = 0.008054825825443934
299999 "gauss_curvature" values
min = -0.0015291390998597254, max = 76.76740941384305, mean = 0.20707488179292724
299999 "mean_curvature" values
min = -0.08668466972546329, max = 0.07247069182534667, mean = 0.0014670715344414843
299999 "orientation_class" values
min = 1, max = 1, mean = 1.0
299999 "kappa_1" values
min = -0.013451171288227006, max = 0.035531235827356206, mean = 0.005613805665819194
299999 "kappa_2" values
min = -0.02394917548321725, max = 0.016954942714376253, mean = -0.0024184508942250034
299999 "gauss_curvature_VV" values
min = -0.00047733807095333636, max = 0.00043302152187133517, mean = 2.976832511371697e-06
299999 "mean_curvature_VV" values
min = -0.015657569756302496, max = 0.021247243840824187, mean = 0.0015976773857970957
299999 "shape_index_VV" values
min = -0.9977120905355646, max = 0.9988476657348505, mean = 0.13633914060829005
299999 "curvedness_VV" values
min = 6.114285811473043e-05, max = 0.025160990621119206, mean = 0.0060341502275246955
299999 "shape_index_cat" values
min = -1.0, max = 1.0, mean = 0.13600212000706668
299999 "verticality" values
min = 63.877864757134944, max = 89.99976482504938, mean = 83.44829409056132
299999 "self_dist_min" values
min = nan, max = nan, mean = nan
299999 "self_id_min" values
min = -1, max = -1, mean = -1.0
299999 "self_dist_far" values
min = nan, max = nan, mean = nan
299999 "self_id_far" values
min = -1, max = -1, mean = -1.0
```
I’ve recently updated the repository with a git pull. I'm running on a Linux remote server but I don't think it's a technical issue, because as I said, it ran for another surface. The only difference is the volume: the subtomo was much smaller 192x192x192 voxels compared to my data with 1024x1024x140 and a similar voxel size. I even used the same config file I used for my colleague and still ran into the same error.

 I'd appreciate any comments and help :) Thank you in advance!

**Comment by bbarad** [comment]
Does your surface visually look like it should have intra-surface contacts? If it is a single relatively flat membrane, it usually will never contact itself along the normal axis, and it would be normal for it to yield no contacts. Absent clathrin coated pits or other blebs or invaginations, I would expect a PM to be pretty low-curvature and flat, so not very likely to have self-contact sites like what you would see in ER or vesicles or mitochondria... with that said, if you see what are likely to be contacts by eye, it may be a problem with processing.

Are you operating in nm or Å mode? I wonder if the long-distance cutoff I am using is too small when operating in Å mode... The cutoff is important for keeping the self-distance computation relatively affordable, but I think it could be increased without too much pain.

**Comment by deglushk** [comment]
No, there seem to be no contact sites and the membrane is indeed quite flat. The curvature measurements make a lot of sense. I had assumed the intra-distance measurement is a calculation of the pairwise spatial distances between points on the same membrane, so I took it as a measure for membrane thickness. Could I have misunderstood its purpose?

Other than that, I'm operating in nm mode and also tried playing around with both the min and max distances between points but that didn't change the RuntimeWarning. The mesh and the .vtp surface file seem fine on visual inspection. I even generated a very fine mesh by tweaking several config parameters, but I still didn’t get any intra-membrane distance measurements.

**Comment by bbarad** [comment]
The self-distance measures by stepping away along the normal axis to identify the nearest piece of the same membrane that isn't "along" the mesh itself. Because of this, it only identifies when you have an "enfolding" like what you see with mitochondrial cristae or if the diameter of the membrane is small enough that the other side of e.g. a vesicle is in range. I'd be happy to chat more about it - the self distance is a strange measurement in some ways, but necessary to avoid every measurement being trivially the neighboring triangle distance (which is a measure of mesh density, not the membrane itself). Sounds like this is expected output so I am going to close this issue, but happy to discuss further how to make the measurement you are looking for.
